# Page settings
baseurl = "http://flatrockbeats.com/#"
title = "FLAT ROCK BEATS"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "cameron oglesby"
  description = "producer from detroit"
  email = "oglesbycam@gmail.com"

  # Navigation
  [params.navigation]
    brand = "FLAT ROCK BEATS"
    home = "Home"
    work = "Beats"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "welcome to the studio"
    subtitle = 'a local producer from detroit'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "browse"
    description = "listen to all my projects on soundcloud."
    url = "https://soundcloud.com/flatrockbeats/tracks"
    button = "soundcloud"
    icon = "icon-social-soundcloud"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "contact"
    description = "reach out me if you are interested in purchasing a beat or creating a custom beat."
    url = "#contact"
    button = "get in touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "purchase"
    description = "once your beat is produced, all project files will be directly emailed to you on a secure link and all copyright will be yours."
    url = "#contact"
    button = "buy a beat"
    icon = "icon-credit-card"
    img = "img_7.jpg"

  [params.intro.video]
    enable = true
    title = "my work"
    icon = "icon-play2"
    url = "***INSERT BEAT URL***"


  # Beats section
  [params.work]
    enable = true
    title = "beats"
    description = "all my beats are produced from either fl studio or ableton live."
    footertext = ''

    [[params.work.row]]
      img = "TIGER WOODS.jpg"
      alt = "Image2"
      title = "Tiger Woods"
      subtitle = "first beat"

    [[params.work.row]]
      img = "The Alpha EP.png"
      alt = "Image2"
      title = "The Alpha EP"
      subtitle = "first ep project"

  # Services section
  [params.services]
    enable = true
    title = "services"
    description = "a guarantee for customer satisfaction"

    [[params.services.item]]
      title = "Name &amp; Strategy"
      description = "flat rock beats will provide the upmost quality and speed when contacting you as a customer."
      icon = "icon-anchor"

      [[params.services.item]]
      title = "Producing &amp; Quality"
      description = "as a self-taught producer, flat rock beats will ensure that an extensive amount of time and care will be provided for each beat published or custom beats you are interested in."      
      icon = "icon-earphones"

  # About section
  [params.about]
    enable = true
    title = "about"
    description = "a self-taught producer from the detroit area."

    [[params.about.item]]
      name = "flat rock"
      position = "cameron oglesby"
      description = "my peanut butter chocolate cake with kool-aid"
      img = "profilepic.jpeg"
      alt = "Person1"
      social = [
        ["icon-twitter", "https://twitter.com/CamOglesby"],
        ["icon-social-instagram", "https://www.instagram.com/cam.oglesby"],
        ["icon-social-soundcloud", "https://soundcloud.com/flatrockbeats"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 14
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "hours spent in the studio"
      icon = "icon-clock"
      from = 0
      to = 182
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "dollars spent on professional equipment"
      icon = "icon-wallet"
      from = 0
      to = 3249
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "satisfied customers"
      icon = "icon-people"
      from = 0
      to = 8
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "bussiness inquiries"
    description = "contact me if you are interested in a beat"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "detroit, mi"],
        ["icon-phone", "(248) 912-2752"],
        ["icon-envelope", "oglesbycam@gmail.com"],
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '2017 &copy; Flat Rock Beats. All Rights Reserved.'
