# Page settings
baseurl = "http://flatrockbeats.com/#"
title = "FLAT ROCK BEATS"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "cameron oglesby"
  description = "producer from detroit"
  email = "oglesbycam@gmail.com"
  # Navigation
  [params.navigation]
    brand = "FLAT ROCK BEATS"
    home = "Home"
    work = "Beats"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "welcome to the studio"
    subtitle = 'a local producer from detroit'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "browse"
    description = "listen to all my projects on soundcloud."
    url = "https://soundcloud.com/flatrockbeats"
    button = "launch to soundcloud"
    icon = "icon-social-soundcloud"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "contact"
    description = "reach out me if you are interested in purchasing a beat, or creating a custom beat."
    url = "[params.contact]"
    button = "get in touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "purchase"
    description = "once your beat is produced, all project files will be directly emailed to you on a secure link and all copyright will be yours."
    url = "#"
    button = "purchase a project"
    icon = "icon-credit-card"
    img = "img_7.jpg"

  [params.intro.video]
    enable = true
    title = "my work"
    icon = "icon-play2"
    url = "***INSERT BEAT URL***"


  # Beats section
  [params.work]
    enable = true
    title = "beats"
    description = "all my beats are produced from either fl studio or ableton live."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"


  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "about"
    description = "a self-taught producer from the detroit area. "

    [[params.about.item]]
      name = "cameron oglesby"
      position = "flat rock"
      description = "idk what to put here yet"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "https://twitter.com/CamOglesby"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 12
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "happy clients"
      icon = "icon-people"
      from = 0
      to = 8
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "bussiness inquiries"
    description = "contact me if you are interested in a beat"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "detroit, mi"],
        ["icon-phone", "(248) 912-2752"],
        ["icon-envelope", "oglesbycam@gmail.com"],
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
